// <auto-generated />
namespace Dealership.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class initial_migration_ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_migration_));
        
        string IMigrationMetadata.Id
        {
            get { return "201504191807552_initial_migration_"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
